### ISSUE TITLE
Blank pages after install Chevereto-Free 1.0.7

### ISSUE THREAD

**Issue by hshamy24** [Chevereto/Chevereto-Free#11]
after i install (Chevereto Free) 1.0.7 on my site i have aproblem with  greate account .. after i add eamil address ,username ,password to signup i got aBlank pages ,,,if i reflash the page i got (this eamil is used) ..so i try to resend  eamil activat but after i add  eamil i used to singup i got aBlank pages again !!!!! 

i try to install (Chevereto Free) 1.0.7 many time but evry time i have same problem

can any one help me about that ??

**Comment by rodolfoberrios** [comment]
Chevereto Free comes "as is". You will need to find the issue on your own.

https://chevereto.com/docs/debug

And this is the first time I learn about this kind of issue, seems to be some local issue at your end.
