### ISSUE TITLE
> Multi-language support has been removed in [1.5.0](https://github.com/rodber/chevereto-free/releases/tag/1.5.0)

### ISSUE THREAD

**Issue by MyBlood** [Chevereto/Chevereto-Free#128]
> Multi-language support has been removed in [1.5.0](https://github.com/rodber/chevereto-free/releases/tag/1.5.0)

Greetings!

What was it for?

_Originally posted by @MyBlood in https://github.com/rodber/chevereto-free/issues/120#issuecomment-979132548_

**Comment by rodber** [comment]
Hi @MyBlood 

Chevereto-Free was overkill before 1.5.0 as it included too much with all the bargain that it means to maintain that. I started to drop features with the intention to get minus maintenance needs for this project and I got rid of languages, bulk importing and moderation.

I'm happy the way the system is now, even taking in consideration that it doesn't work in my native language (Spanish).

I hope that my reply answers your concern.

**Comment by MyBlood** [comment]
> Hi @MyBlood
> 
> Chevereto-Free was overkill before 1.5.0 as it included too much with all the bargain that it means to maintain that. I started to drop features with the intention to get minus maintenance needs for this project and I got rid of languages, bulk importing and moderation.
> 
> I'm happy the way the system is now, even taking in consideration that it doesn't work in my native language (Spanish).
> 
> I hope that my reply answers your concern.

Yes, your answer is quite clear to me, thank you.
