### ISSUE TITLE
Uploading using url through the API seems broken

### ISSUE THREAD

**Issue by leonluc-dev** [Chevereto/Chevereto-Free#130]
When using the api to upload an image like this `https://myserver.com/api/1/upload?key=api-key&format=json&source=https%3A%2F%2Fexample.com%2image.jpg` the api cannot process the image.

This seems related to this particular bit of code:

https://github.com/rodber/chevereto-free/blob/0dce5d537421cac616b160de391562167bda6cc6/app/routes/route.api.php#L61-L63

At line 61 the `$source` variable is already plaintext (url decoded). However, the `G\getQsParams()['source'];` returns an url encoded value and sets the source variable to it.
This is causing the `CHV\Image::uploadToWebsite($source);` call to return "invalid file type" (since it cannot handle url encoded values)

**Comment by rodber** [comment]
Try using `POST`.

**Comment by leonluc-dev** [comment]
`POST` using a x-www-form-urlencoded body with the same params does work. Thanks for the tip!

I wasn't aware `POST` was required due to [the docs](https://chevereto-free.github.io/api/#api-call) mentioning support for `GET`
