### ISSUE TITLE
00:05:11 RecursiveDirectoryIterator::__construct(/var/www/html/app/install/update/temp/-/): failed to open dir: No such file or directory

### ISSUE THREAD

**Issue by ghost** [Chevereto/Chevereto-Free#136]
00:05:11 RecursiveDirectoryIterator::__construct(/var/www/html/app/install/update/temp/-/): failed to open dir: No such file or directory
![image](https://user-images.githubusercontent.com/49315644/147381921-db3805c7-d672-43e6-8b76-25ffd199688d.png)

**Comment by rodber** [comment]
If fails, go with manual update.

https://chevereto-free.github.io/setup/server/updating.html
