### ISSUE TITLE
Issues upgrading from 1.4.0 to latest (1.6.1)

### ISSUE THREAD

**Issue by iamdoubz** [Chevereto/Chevereto-Free#138]
Using web updater, I get the following error:

```
11:41:09 Can't connect to %s
11:41:08 Attempting to extract v1.6.1
11:41:08 Downloaded v1.6.1, proceeding to extraction
11:41:07 Starting v1.6.1 download
11:41:07 Update needed, proceeding to download
11:41:07 Last available release is v1.6.1
11:41:07 Installed version is v1.4.0
```

My nginx error log is as follows:

```
2022/01/03 11:51:41 [error] 422361#0: *3 FastCGI sent in stderr: 
	"PHP message: RecursiveDirectoryIterator::__construct(/var/www/chevereto/app/install/update/temp/-/): 
		failed to open dir: No such file or directory" while reading response header from upstream, 
		client: my.ip.add.res, 
		server: chevereto.my.domain, 
		request: "GET /update/?auth_token=31eae3ldlotpeot9nwm3b4d815739f99417db97b4fb&action=extract&file=rodber-chevereto-free-1.6.1-0-g938559a_d02cf99df8991a57f0673533.zip&_=1641232292488 HTTP/2.0", 
		upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", 
		host: "chevereto.my.domain", 
		referrer: "https://chevereto.my.domain/update/?auth_token=31eae3ldlotpeot9nwm3b4d815739f99417db97b4fb"
```

## My system specifics:
- nginx 1.21.4
- php-fpm 7.4.27
- 5.5.5-10.3.32-MariaDB-0ubuntu0.20.04.1

Any help appreciated! Thank you in advanced for maintaining the free version of Cheverto for us poor folk.

**Comment by nesxo** [comment]
> Using web updater, I get the following error:
> 
> ```
> 11:41:09 Can't connect to %s
> 11:41:08 Attempting to extract v1.6.1
> 11:41:08 Downloaded v1.6.1, proceeding to extraction
> 11:41:07 Starting v1.6.1 download
> 11:41:07 Update needed, proceeding to download
> 11:41:07 Last available release is v1.6.1
> 11:41:07 Installed version is v1.4.0
> ```
> 
> My nginx error log is as follows:
> 
> ```
> 2022/01/03 11:51:41 [error] 422361#0: *3 FastCGI sent in stderr: 
> 	"PHP message: RecursiveDirectoryIterator::__construct(/var/www/chevereto/app/install/update/temp/-/): 
> 		failed to open dir: No such file or directory" while reading response header from upstream, 
> 		client: my.ip.add.res, 
> 		server: chevereto.my.domain, 
> 		request: "GET /update/?auth_token=31eae3c7cd2ce8463b4d815739f99417db97b4fb&action=extract&file=rodber-chevereto-free-1.6.1-0-g938559a_d02cf99df8991a57f0673533.zip&_=1641232292488 HTTP/2.0", 
> 		upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", 
> 		host: "chevereto.my.domain", 
> 		referrer: "https://chevereto.my.domain/update/?auth_token=31eae3ldlotpeot9nwm3b4d815739f99417db97b4fb"
> ```
> 
> ## My system specifics:
> * nginx 1.21.4
> * php-fpm 7.4.27
> * 5.5.5-10.3.32-MariaDB-0ubuntu0.20.04.1
> 
> Any help appreciated! Thank you in advanced for maintaining the free version of Cheverto for us poor folk.

Did you deployed the chevereto in a docker container and tried to update it using dashboard ?

**Comment by iamdoubz** [comment]
I do not use docker for chevereto, but good question.

**Comment by nesxo** [comment]
> I do not use docker for chevereto, but good question.

ok, it may be dangerous to paste your auth_token and url's path  in a public area.

**Comment by rodber** [comment]
If the web updater fails simply try with manual process.

https://chevereto-free.github.io/setup/server/updating.html#manual-update
