### ISSUE TITLE
Support Ambiguous Characters for Admin Password

### ISSUE THREAD

**Issue by k0nsl** [Chevereto/Chevereto-Free#14]
Chevereto-Free currently doesn't support ambiguous characters (any length?) in the user password. I tried length 35 and up, none worked. So perhaps there is a limitation in the length and actually not an issue with support for ambiguous characters? I have not looked at the code, yet.

Either way, if there is no support for ambiguous characters then consider adding support for it, or if there is a limitation in the length of the password (e.g 25 characters, or whatever), then consider increasing this limit to a higher number. I try not to use a password which is less than 25 characters unless I am forced to do so for whatever reason.

Best wishes,
-k0nsl

**Comment by rodolfoberrios** [comment]
Passwords are soft fixed to {6,32} if you want to tweak that then edit this file https://github.com/Chevereto/Chevereto-Free/blob/master/app/lib/classes/class.settings.php
