### ISSUE TITLE
v1.6.2 not available ( actual version 1.6.1)

### ISSUE THREAD

**Issue by LiloBzH** [Chevereto/Chevereto-Free#140]
Hi

Chevereto 1.6.1 dont find this new version.
"This website is running latest Chevereto Free version"

**Comment by rodber** [comment]
![18KyYS](https://user-images.githubusercontent.com/20590102/148610565-66c004d3-6e01-455b-9f08-5571d07d3b83.gif)

Try now.

**Comment by LiloBzH** [comment]
patch ok but HTTP ERROR 500 on /install page. 

i m watching log

**Comment by LiloBzH** [comment]
PHP Parse error:  syntax error, unexpected ':', expecting ')' in /var/www/xxxxxxxx/xxxxxxxxxxxx/app/vendor/chevere/chevere/src/Chevere/Components/Filesystem/functions.php on line 49"

**Comment by rodber** [comment]
Oops... 😅

**Comment by LiloBzH** [comment]
New release is ok ;)
