### ISSUE TITLE
LANGUAGE automatically changed itself and there is missing settings to set up

### ISSUE THREAD

**Issue by pipetko** [Chevereto/Chevereto-Free#166]
Language was Bulgarian, after Update it became English. I tried to find the Lang settings menu and it is MISSING!!!

**Comment by rodber** [comment]
Support for multi-languages has been removed from Chevereto-Free.
👉 https://github.com/rodber/chevereto-free/issues/128
👉 https://github.com/rodber/chevereto-free/releases/tag/1.5.0
