### ISSUE TITLE
SVG logo displays wrong in edge

### ISSUE THREAD

**Issue by adamxp12** [Chevereto/Chevereto-Free#19]
Before I talk about the issues I must say this is blooming awesome. one of my favourite self host apps to date.

But SVG logos display very oddly in edge

Edge: http://prntscr.com/godyo2
Chrome: http://prntscr.com/godyv3

SVG is a must as no matter how I do the raster logo I see jagged edges around the text where the browser is scaling it down to fit.

It appears to be a edge bug as it cant display SVG's without explicit width/height values on the img element. but that's kinda a pain.

Would it be possible to have edge failback to PNG instead of SVG as it works fine in other browsers. and it don't seem to be possible to set static width/height as it breaks the SVG display in ff/chrome

**Comment by rodolfoberrios** [comment]
Default logo works on Edge. Check your editing or your SVG file.
![image](https://user-images.githubusercontent.com/20590102/30753587-196a2a74-9f96-11e7-9666-4721ad790e25.png)

Please remember that Chevereto-Free is provided "as-is". There is a community-based support forum where you can ask other users directly, here: https://chevereto.com/community/forums/cheverto-free-support-community-based.85/
