### ISSUE TITLE
Install 404s

### ISSUE THREAD

**Issue by mwcz** [Chevereto/Chevereto-Free#21]
After extracting and setting up the permissions correctly, the install simply fails with:

```
Not Found

The requested URL /cheverato/install was not found on this server.
```

OS: Fedora 27, using Apache.  SELinux enabled and `httpd_sys_rw_content_t` applied to all the dirs listed in the docs that need write.

**Comment by mwcz** [comment]
It may also be worth noting that the settings file that was automatically created at `app/settings.php` is an empty file.

**Comment by rodolfoberrios** [comment]
Rewrite issue, check your vhost configuration. /install relies on URL rewriting so make sure that everything works properly in your server.

**Comment by mwcz** [comment]
Good call.  It was not any custom rewrites (I'm using the unmodified default Apache config file for Fedora), but I did notice `.htaccess` files are disabled by default.  Fixed and fixed.  Thanks!
