### ISSUE TITLE
Is there a way to auto-syncronize an album with a directory of images?

### ISSUE THREAD

**Issue by mwcz** [Chevereto/Chevereto-Free#22]
I would like to "post" images to Chevereto by placing them in a folder.  This might be done by FTP, Dropbox sync, manual copying, etc.  Is there a way for Chevereto to look at a local folder for its images instead of manual uploading?

Thanks!

**Comment by rodolfoberrios** [comment]
No, at this time there's no such functionality.

**Comment by mwcz** [comment]
Good to know, thank you!
