### ISSUE TITLE
Redirect to /install

### ISSUE THREAD

**Issue by plaidshirtakos** [Chevereto/Chevereto-Free#29]
I get auto redirect to folder /install, which doesn't exists. /app/install/installer.php gives error message: 

> This file cannot be directly accessed.

**Comment by rodolfoberrios** [comment]
Check if URLs rewriting is working properly. /install should be handled by /index.php

**Comment by plaidshirtakos** [comment]
Yes, I enabled it, I got error message, when it was disabled.

**Comment by plaidshirtakos** [comment]
It is not resolved yet.

**Comment by rodolfoberrios** [comment]
Yeah, but the problem is your server. Not Chevereto.

**Comment by plaidshirtakos** [comment]
What setting should I check on server?

**Comment by rodolfoberrios** [comment]
Allow override under your vhost. The fact that you enable mod rewrite doesn't mean that it will just work.

**Comment by plaidshirtakos** [comment]
Thank you, problem resolved.

**Comment by lop1992** [comment]
How ?

**Comment by bykidi** [comment]
> 
> 
> How ?

#7

**Comment by lop1992** [comment]
> 
> 
> > How ?
> 
> #7

Thank you
