### ISSUE TITLE
PHP7.2.3 integrity-check.php minor warning

### ISSUE THREAD

**Issue by CryptoSiD** [Chevereto/Chevereto-Free#30]
I installed the latest version using the installer and I'm getting this warning in the error log.

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/Chevereto-Free/app/lib/integrity-check.php on line 168"

**Comment by rodolfoberrios** [comment]
Chevereto-Free is not yet compatible with PHP 7.2+. Remember that this thing always 6 months behind the paid edition and PHP 7.2 support was added on [January 26th 2018](https://chevereto.com/releases#v3_10_8).
