### ISSUE TITLE
Scrolling broken on mobile

### ISSUE THREAD

**Issue by biffhuxtable** [Chevereto/Chevereto-Free#33]
Upgraded from Chevereto free 1.0.9 to 1.0.10 and scrolling no longer works on mobile. Seems similar to [this issue](https://chevereto.com/community/threads/admin-swipe-scrolling-on-tablets.8794/), except I'm using an iPhone. Scrolling does work when using 2 fingers. Have the same issue on multiple phones.

**Comment by rodolfoberrios** [comment]
Please read the whole issue.

Chevereto Free is always behind the paid edition. Is not flawless and it doesn't include all features.

**Comment by rodolfoberrios** [comment]
Fixed on v1.0.11
