### ISSUE TITLE
404 on /install page after installing php7.0-curl

### ISSUE THREAD

**Issue by bykidi** [Chevereto/Chevereto-Free#4]
before installing php7.0-curl
![default](https://cloud.githubusercontent.com/assets/1337953/18414572/5e04e6d4-77d7-11e6-9d7e-1a5aeed102c5.PNG)

after installing php7.0-curl and php-curl i got 404 error redirecting to /install

php7.0-curl is already the newest version (7.0.10-2+deb.sury.org~xenial+1).

**Comment by bykidi** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/18414618/020288a2-77da-11e6-9960-527cf17d185c.PNG)

**Comment by rodolfoberrios** [comment]
Regardless of what php_info() says, the system [detects the presence of cURL](https://github.com/Chevereto/Chevereto-Free/blob/master/app/lib/integrity-check.php#L50) by checking if [curl_exec](http://php.net/manual/en/function.curl-exec.php) exists in the global scope.

**Comment by bykidi** [comment]
After entire php reinstall i only got error about missing mod_rewrite, but as soon as i do a2enmod rewrite i get same white page on host.domain/install redirected from host.domain, doesn't matter if i got php7.0-curl installed or not

**Comment by rodolfoberrios** [comment]
I'm afraid that you will need to look further in your server setup and not because mod_rewrite is installed it means that it will work as expected. Mod rewrite often fails when you forgot to tune your Allow Override settings.

**Comment by bykidi** [comment]
Fixed it by myself, solution was pretty easy
http://askubuntu.com/questions/421233/enabling-htaccess-file-to-rewrite-path-not-working

**Comment by rodolfoberrios** [comment]
Yeah, it seems that I pointed in the right direction every time.
