### ISSUE TITLE
embed / pup not redirecting or inserting into textarea.

### ISSUE THREAD

**Issue by dessalines** [Chevereto/Chevereto-Free#41]
chevereto version: `docker  image: nmtan/chevereto:1.1.3`

Chevereto is running fine locally, it uploads images correctly, and the pup button displays and opens up a new browser window correctly. However after I upload, instead of filling my textarea, it just sends me to an "upload complete" page, giving me the wrong links. In another example [here](https://codepen.io/anon/pen/jQQvGP), it should correctly close the window and insert the chosen insert format into an open textarea.

I'm not sure if this has to do with the docker image, or a bad setting, but it doesn't fill the texarea.

html:
```
<textarea name={this.id} id={this.id} />
<script async src="http://localhost:8098/sdk/pup.js" data-url="http://localhost:8098/upload" data-auto-insert="markdown-embed-full" data-palette="green" data-target={`#${this.id}`}></script>
```
edit: I also checked and it does look like correct GUIDs are getting set on the textarea.

**Comment by rodolfoberrios** [comment]
Hi, @dessalines 

Thank you for reporting this.

Could you confirm that this happens with zero browser extensions or add-ons? I have been told that some browser extensions are causing PUP to fail.

**Comment by dessalines** [comment]
I did try it without browser extensions, it still fails. Even with browser extensions, the version on your codepen inserts fine, but when served from localhost, to a locally running app, it doesn't

**Comment by rodolfoberrios** [comment]
It works perfect on my local.

You will need to write the procedure required to to replicate this, step by step with all details.
