### ISSUE TITLE
Embed / PUP not inserting into textarea where cursor is Located.

### ISSUE THREAD

**Issue by dark-1** [Chevereto/Chevereto-Free#42]
Hi !!! rodolfoberrios ,
First off , Thanks for `Chevereto-Free` . 😍 

Here's my Issue : 
Say , I have a textarea with following text : 
```
Text1

Text2
Text3
```
Now , I want to insert image after `Text1` & before `Text2` ,
so i move my cursor after `Text1` like this : 
```
Text1
|
Text2
Text3
```
assume the symbol `|` is location of my cursor.
Now , i click the `Upload images` button , then upload the image , it gets successfully uploaded...
Then, This is what I expect : 
```
Text1
[img]https://demo.chevereto.com/images/2019/10/03/Lenna_test_image.png[/img]
Text2
Text3
```
But , This is what happens :
```
Text1

Text2
Text3
[img]https://demo.chevereto.com/images/2019/10/03/Lenna_test_image.png[/img]
```
So , what should I do , that the `pup.js` will insert at location of my cursor ???

Thanking you , Best regards 👍

**Comment by rodolfoberrios** [comment]
https://github.com/Chevereto/Chevereto-Free/blob/master/sdk/pup.dev.js#L738

**Comment by dark-1** [comment]
@rodolfoberrios Sir ,

May I know , what should I do at that line ???

Thanking you , Best regards 👍

**Comment by rodolfoberrios** [comment]
Honestly, I don't know.

My design never included following the cursor for every vendor. It follows the cursor when the editor provides that functionality, I didn't bother myself with the trouble of making that standard for every vendor.

**Comment by dark-1** [comment]
Ahh!!! ok, 
so is there any vendor with that functionality ??? , so that I can learn from it ...
I use phpBB...

Thanking you , Best regards 👍

**Comment by rodolfoberrios** [comment]
I'm sorry, I don't have such information. Please don't use an issue to chat about how to achieve what you want. This is not a forum, is a software issue tracker.

**Comment by dark-1** [comment]
Ok Sorry... 🙏 
This is Last message from me.
Thank you , Bye , Best regards 👍
