### ISSUE TITLE
 Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /www/chevereto/lib/G/functions.php on line 254

### ISSUE THREAD

**Issue by StrangerLi** [Chevereto/Chevereto-Free#45]
When I upgraded the PHP version to 7.3, the following error occurred. According to the documentation, this error is a syntax error. 

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /www/chevereto/lib/G/functions.php on line 254

**Comment by rodolfoberrios** [comment]
Chevereto Free doesn't support PHP 7.3 yet.
