### ISSUE TITLE
Chevereto-1.1.4 PHP Code Execution Vulnerability

### ISSUE THREAD

**Issue by Invi0sible** [Chevereto/Chevereto-Free#46]
**Hi,I found a php code execution vulnerability at Chevereto-1.1.4
when log in as admin,"Settings > Pages " to add an evil page:**
![image](https://user-images.githubusercontent.com/33925178/67136954-93163880-f260-11e9-9c11-ab8f10339a00.png)
![image](https://user-images.githubusercontent.com/33925178/67136959-a1645480-f260-11e9-93f4-86ba93b0aa13.png)
![image](https://user-images.githubusercontent.com/33925178/67136968-b8a34200-f260-11e9-983f-16b5173ed135.png)

**visit the evil file via http://10.211.55.8/Chevereto/page/url-key**

![image](https://user-images.githubusercontent.com/33925178/67136972-c22caa00-f260-11e9-9804-2ee08eac6a84.png)

**Comment by rodolfoberrios** [comment]
Not a bug, this is intended.
