### ISSUE TITLE
deleted files using site are not being deleted

### ISSUE THREAD

**Issue by ghost** [Chevereto/Chevereto-Free#47]
When deleting using /explore/recent with the bulk deleter, all of the files selected to be deleted no longer show up on the web interface, but are still in the image folders on the server
Would you also be so kind as to add a button or script to scan the image directory and remove lose files so that this is easier to clean up?
thank you

**Comment by rodolfoberrios** [comment]
Please note that Chevereto doesn't serve your images. Your server does.

If you delete an image and the server still resolves the image is not a problem of the software, is your server/CDN.

**Comment by Ralthazoth** [comment]
Checking that the filesystem has deleted the file that php requested to be deleted before marking the image as deleted in the database would at least warn your users that their server refused to delete the file. Further what could possibly be causing that to fail, sporadically even as some deletions are succeeding on both of my uses of chevereto? I saw this behavior on both a Hetzner VPS running ubuntu / ubuntu repo litespeed(php 7.2.19), and DreamHost's shared instance running apache(php 	7.3.10).

**Comment by rodolfoberrios** [comment]
This is how the software delete local files ([app/lib/classes/class.image.php](https://github.com/Chevereto/Chevereto-Free/blob/75c119d8c6ef9fc07804ebaf19ddfa53ec8c1189/app/lib/classes/class.image.php#L1128)):

```php
                    if (file_exists($file_delete) and !@unlink($file_delete)) {
                        throw new ImageException("Can't delete file", 200);
                    }
```
The software already does the check you mention, is your file system which is not working properly.
