### ISSUE TITLE
Security issue in sharing function!

### ISSUE THREAD

**Issue by intervisionlord** [Chevereto/Chevereto-Free#48]
Hello! (and sorry for my english - not my native...)

I have an album with access by link.
And i have sevaral images in it. So, i think if i want to share whole album i sent link on it and if i want to share only 1 image i sent link only on this image.

But!

When i share image link and try to open it (not loged in) i can see all contents on album where this image locates but i share only image not a whole album! why so?

I think that should not be like this.

**Comment by rodolfoberrios** [comment]
The system is designed to inherith permissions based on albums. When you share an image inside an album is understood that you also share the album.

That's the way it has always worked.

**Comment by intervisionlord** [comment]
so, if i need to share only 1 image, i need to create separete album for this concrete image only?
And if i have several images which i need to share among different people i need to create several albums for it?

Sounds like something non-logical...

**Comment by rodolfoberrios** [comment]
Like I said, the permissions are applied via albums. The system is designed in this way. It was shaped by user feedback in this way.

If you have a better idea on how it should work then suggest it here: https://chevereto.com/community/collaboration/
