### ISSUE TITLE
Wrong usage of Day, Days (few), Days (multiple) in Russian localization

### ISSUE THREAD

**Issue by bykidi** [Chevereto/Chevereto-Free#5]
![1](https://cloud.githubusercontent.com/assets/1337953/18418298/c7c8b4f0-784b-11e6-8b43-017f76d426bc.PNG)
После 5 минут - Correct
После 30 минут - Correct
После 1 час - Correct
После 2 часа - Correct
После 6 часов - Correct
После 12 часов - Correct
После 1 день - Correct
После 2 дня - Wrong

Should be like this:
Через 5 минут - Correct
Через 30 минут - Correct
Через 1 час - Correct
Через 2 часа - Correct
Через 6 часов - Correct
Через 12 часов - Correct
Через 1 день - Correct
Через 2 дня - Correct

**Comment by bykidi** [comment]
Correct usage for days
After 1 day - Через 1 день
After 2 days - Через 2 дня
After 3 days - Через 3 дня
After 4 days - Через 4 дня
After 5 days - Через 5 дней
After 6 days - Через 6 дней
/etc etc/

**Comment by rodolfoberrios** [comment]
Thanks you, but translations are handled at [OneSky](http://translate.chevereto.com/) platform, not here.
