### ISSUE TITLE
There is a warning when using `continue` inside `switch` in php7.3

### ISSUE THREAD

**Issue by xiebruce** [Chevereto/Chevereto-Free#51]
Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /path/to/Chevereto-Free/lib/G/functions.php on line 254

should I modify `continue` to `break` or to `continue 2`?

**Comment by rodolfoberrios** [comment]
For now, I recommend running it under PHP 7.2 unless you feel confortable patching this on your own in your installation.

There are plans for a new fork (taken from Chevereto v3.14) which will carry support for PHP 7.4, must-have security patches and many other new features. Unfortunately, my schedule is totally collapsed between the support for the paid version and the [new framework](https://github.com/Chevereto/chevere) that I am creating for Chevereto 4.

The availability of this eventual new version for Chevereto-Free would be by mid-March if everything goes well. I'm sorry for the issues this may cause to you, but I don't have the man power neither the resources to do it earlier.

**Comment by xiebruce** [comment]
Got it, thank you for your work, actually it works fine after I modify `continue` to `continue 2`, so, I'll use it until your new version is available.
