### ISSUE TITLE
Bulk importer page does not exist

### ISSUE THREAD

**Issue by crypdick** [Chevereto/Chevereto-Free#54]
Hello, I am trying to evaluate Chevereto. I installed with Docker, persistently mounted an image dir, and tried to navigate to `dashboard/bulk` as per [the bulk importer docs](https://chevereto.com/docs/bulk-importer). I get a page does not exist error.

**Comment by rodolfoberrios** [comment]
The Bulk Content importer is included only in the paid edition at this time. This functionality should get added to the next Chevereto-Free release (no release date).
