### ISSUE TITLE
about the location of calling js

### ISSUE THREAD

**Issue by colorfulshadowty** [Chevereto/Chevereto-Free#57]
sorry to disturb you,but here are some questions:(excuse for my poor English please)</br>
i'm trying to find out where you call js(maybe 'call'.translated on bing),i need to put it on my github to use jsdelivr CDN,because it was so slow if i load it from my website</br>
![sample](https://cdn.jsdelivr.net/gh/colorfulshadowty1/img/img1/20200414220417.png)</br>
i hope you can tell me  where it call js so that i can change the url to what i want</br>
thanks a lot</br>
hope for your reply!

**Comment by rodolfoberrios** [comment]
You can use a CDN for the static assets. Go to Dashboard > Settings > External services

https://chevereto.com/docs/cdn

**Comment by colorfulshadowty** [comment]
thanks for your reply！
but,a little problem,you may not know, jsdelivr CDN is free and it only can be used to speed up files on GitHub,so I’m not able to use the method like you said .
Hope to your reply,if you can give me where the location is(like <script ‘’ .....>)
Thanks a lot!

**Comment by rodolfoberrios** [comment]
`grep -rl --include=\*.php "chevereto.js" /path`
