### ISSUE TITLE
Upload using Curl / wget

### ISSUE THREAD

**Issue by IIPoliII** [Chevereto/Chevereto-Free#59]
Hey I am interested in the paid version. But I want to know if it's possible to upload via curl or wget and get the URL back as response?

**Comment by rodolfoberrios** [comment]
A response as a redirect? Yes.
A response as a string representing the URL. Yes.

https://chevereto.com/docs/api-v1

**Comment by IIPoliII** [comment]
Mhmm intressting do you have any exemple for it?
