### ISSUE TITLE
Uploading Images Issue

### ISSUE THREAD

**Issue by akiraaisha** [Chevereto/Chevereto-Free#6]
Hi,I have two issues.  I'm having problems uploading images at my site. Whenever I upload _GIFS_ from my Computer, it prompts me **"Some files couldn't be added."**. 
Then the second issue is, after I upload the GIFs and get the error _(I didnt clicked Exit afterwards)_, then immediately pasted an Image Url from Giphy and it works fine **_with my Direct Upload_**. So basically it duplicates my GIFS from my Upload and the Image Url. (I think it's a **bug**)

> Details
> My website is [https://moecafe.us](url)
> I'm using Free Chevereto.
> chmod 777 /content /images
> chown -R root:root chevereto/
> I'm using XAMPP.

**Comment by rodolfoberrios** [comment]
It is impossible to debug this if your installation doesn't allow public uploads.

**Comment by akiraaisha** [comment]
I enabled now with Guest Uploads. It still prompts the notice even at Guest mode.

**Comment by rodolfoberrios** [comment]
Enabling or disabling guest uploads won't make the issue to disappear, it just allows me to test it out.

**Comment by akiraaisha** [comment]
So, I have to enable Debug Mode? (I set the Level into 3).

**Comment by rodolfoberrios** [comment]
The problem isn't Chevereto:

> Refused to load the image 'blob:https://moecafe.us/a0b03afb-fd3d-4ae8-a894-07835aaf4f40' because it violates the following Content Security Policy directive: "img-src * data:".

Refer to these:
https://content-security-policy.com/
https://developers.google.com/web/fundamentals/security/csp/

**Comment by akiraaisha** [comment]
F*k, I tot I don't have problems with CSP anymore. I just disabled CSP header in Apache, and now it works fine now. Thank you a bunch!

**Comment by rodolfoberrios** [comment]
Glad to to help.
