### ISSUE TITLE
Image upload size limit ignores php.ini settings

### ISSUE THREAD

**Issue by BobAnkh** [Chevereto/Chevereto-Free#60]
I installed Chevereto using:

> Ubuntu 18.04 LTS
> Apache/2.4.29 (Ubuntu)
> mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper
> PHP v7.3.17-1

The limit of uploading images is 2M and I would like to have larger images.

However I changed `/etc/php/7.3/fpm/php.ini` but nothing happened. The limit showed on the dashboard is still 2M.

What I've changed:

> upload_max_filesize = 100M;
> post_max_size = 100M;
> max_execution_time = 300;
> memory_limit = 256M;

I have seen this issue #53 , but I am not familiar with mysql so I don't know what should be done to change the image size limit.

Could anybody help me deal with it?

Thank you!

**Comment by dfmcvn** [comment]
Did you adjust the setting in your Dashboard?

`hxxps://thesite.com/dashboard/settings/image-upload`

the `Maximum upload file size` option.

**Comment by BobAnkh** [comment]
![image](https://user-images.githubusercontent.com/44333669/80898261-f9ae0000-8d33-11ea-9dbf-b3711f912c85.png)
Do you mean here? It seems that I cannot change to a number larger than 2(It will refuse to accept it)

Though I actually change the values in php.ini but here in dashboard the setting seems ignore them?

**Comment by dfmcvn** [comment]
A lil bit weird, but did you restart php-fpm to apply these configs?

**Comment by BobAnkh** [comment]
Yes after changing my php.ini I use `systemctl restart php7.3-fpm.service` to restart and also `service apache2 restart`.

Is the command I use not correct? I just don't know what happened.

**Comment by dfmcvn** [comment]
I have no clue if the command is right or not, I just `service php-fpm restart` (I'm using CentOS) and the Dashboard shows the correct values.

![IMG_20200503_112439](https://user-images.githubusercontent.com/22710598/80898713-bd2cd500-8d30-11ea-88e5-7ac518929498.jpg)

I think this is an server-related issue, not a problem from the script.

**Comment by BobAnkh** [comment]
Ok I think I can try to reinstall it

**Comment by BobAnkh** [comment]
I find out what caused it.

I modify the wrong php.ini

With apache2 and php, I should modify /etc/php/7.3/apache2/php.ini

Leave this as a note for others
