### ISSUE TITLE
Problem 1.2.0

### ISSUE THREAD

**Issue by hamersky** [Chevereto/Chevereto-Free#67]
After upgrade have error
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function get_page_tos()

**Comment by rodolfoberrios** [comment]
I'm unable to reproduce the issue, so either you didn't applied all files during the update or you need to provide the context for this message so I can actually replicate this in a test environment.

**Comment by hamersky** [comment]
Ok I found solution.
Problem exist if not have translation "Terms of service"

**Comment by rodolfoberrios** [comment]
Could you provide more details? I need to know where is the problem to patch the software.

**Comment by hamersky** [comment]
perhase "Terms of service" it must be translated if you change the default language

**Comment by rodolfoberrios** [comment]
When no translation the system uses the value passed to gettex. Explain how missing a translation causes this issue.

**Comment by rodolfoberrios** [comment]
The problem wasn't the translation, but the function used to define `page_tos`. The commit [080c350](https://github.com/Chevereto/Chevereto-Free/commit/080c35091387f0388c33d071078780fbdbdfad07) fixes this issue.
