### ISSUE TITLE
http 404 - install folder missing

### ISSUE THREAD

**Issue by TheReal1604** [Chevereto/Chevereto-Free#7]
If i try to install via the tar.gz package on my webserver, the index.php redirects me to mydomain.com/install . But the Install folder and its content is not included in the .tar.gz or .zip you released. 

![image](https://cloud.githubusercontent.com/assets/5877910/20076019/0c41bef2-a537-11e6-9c3b-59a071417fc9.png)

![image](https://cloud.githubusercontent.com/assets/5877910/20076107/6f58e560-a537-11e6-87a1-9aa511368e19.png)

**Comment by rodolfoberrios** [comment]
You need mod_rewrite or configure your nginx rewrite rules. Check this:

https://chevereto.com/docs/requirements

**Comment by TheReal1604** [comment]
@rodolfoberrios sry that I disturb you with this misconfiguration on my site. Just for documentation, after inserting this:

`<Directory /var/www/chevereto >
                        Options Indexes FollowSymLinks MultiViews
                        AllowOverride All
                        Order allow,deny
                        allow from all
                </Directory>`

All is working like a dream.

Thanks!
