### ISSUE TITLE
No A-Z sorting in 1.2.2

### ISSUE THREAD

**Issue by kiriya-aoi** [Chevereto/Chevereto-Free#70]
From the patch notes for 1.2.0:
>Added album image sort A-Z [10452]

Is there a Dashboard setting needed to enable this? On updating to 1.2.2 (from 1.1.4) the A-Z option does not appear in my albums.

**Comment by rodolfoberrios** [comment]
Hi @kiriya-aoi,

Unfortunately I made a mistake and the album (and user) A-Z sort is completely missing. However, it was my intention to add this functionality so I will push it in the next revision, which should be released within this week.
