### ISSUE TITLE
Blank pages after PHP 7.1 upgrade

### ISSUE THREAD

**Issue by bykidi** [Chevereto/Chevereto-Free#8]
Hi! Today i upgraded my PHP from 7.0 to 7.1 and now every chevereto page is blank, but pages title are still present.
Is chevereto 1.0.5 compatible with latest PHP at all?
Thanks.

**Comment by rodolfoberrios** [comment]
"Blank page" doesn't tell me anything. Please give me error_log output.

**Comment by bykidi** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/21728871/86109b30-d459-11e6-9ff8-0cf1df367fbc.PNG)

**Comment by bykidi** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/21728936/d609a528-d459-11e6-8ea6-6d9d5040b1a5.PNG)

That's all i got.
error.log is empty
access log is fine too

**Comment by rodolfoberrios** [comment]
I will check it out.

**Comment by rodolfoberrios** [comment]
![image](https://cloud.githubusercontent.com/assets/20590102/21729210/d9dbc52c-d428-11e6-98a2-b5a311506c39.png)

Demo has been patched and works with PHP 7.1. I will roll the update within this week for the paid edition. Free edition will get the patch by the end of the next week.

**Comment by bykidi** [comment]
Thanks!
