### ISSUE TITLE
Tag images

### ISSUE THREAD

**Issue by xomikronx** [Chevereto/Chevereto-Free#9]
I'm trying to figure out how to tag an image.  Right now, the title's are being indexed for searches, but it only indexes if the word is 4 characters or longer.  

Is there a way to properly tag an image?

**Comment by rodolfoberrios** [comment]
Search index use those:

`FULLTEXT KEY `searchindex` (`image_name`,`image_title`,`image_description`,`image_original_filename`)`

Which will depend on how your DB engine handles Fulltext searches (InnoDB, MyISAM).

Regarding tags, I'm sorry but at this time Chevereto doesn't feature tags. There are plans to add tags but I can't say a version or date.

**Comment by xomikronx** [comment]
Thanks @rodolfoberrios.

How would I change it so that it indexes 3 characters or more?

**Comment by rodolfoberrios** [comment]
Refer to the official MySQL documentation for that: http://dev.mysql.com/doc/refman/5.7/en/fulltext-fine-tuning.html
