### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by rodber** [chevereto/Chevereto-Free#91]
Dear Chevereto-Free community,

Update: https://github.com/chevereto/Chevereto-Free/issues/91#issuecomment-900371084

> If I get maintainers I commit myself to provide a legacy long-term edition that should work up to 2024

I will [close my chapter](https://rodolfo.is/2021/06/25/adios-chevereto-free/) with Chevereto-Free later this year but that doesn't means that it should also end for you. The value of Open Source is that we can distribute software so others can re-use it, re-shape it, improve it. The spirit of Open Source is not to have one team / company working in everything, but all users involved.

I never managed to drive contribution neither collaboration in this project the way Open Source should be, perhaps other team can do better or at least take charge to keep it relevant for existing users of this software. You can do this with and without my permission, the license allows you to do that. Just let me know to link you.

I really hope that Chevereto-Free (or a fork) can keep providing updates so users won't be forced to pay or leave.
If you ever wanted to collaborate here, this is the time. If you strongly believe in Open Source then help me to save this project from deprecation.

Thanks,
Rodolfo.

**Comment by Windyo** [comment]
Hey,

I can't contribute to the project as i miss any technical knowledge that would be useful, but has there been consideration given to just do a "softwall" wherein paid features exist in the codebase but are just blocked behind a license key access ?
That could simplofy release while leaving you free to work on revenue generating steams. 
Cheers and thanks for the contributions you made over the years.

**Comment by rodber** [comment]
@Windyo

What I was trying to do with Chevereto V4 was a common Open Source base for Chevereto and [monetize it](https://rodolfo.is/2021/02/03/monetizing-chevereto/) with addons + extras. Unfortunately, that process didn't got any third-party developers attention so I figured out that it will be really hard and exhausting to do it on my own. I even made all [this](https://chevere.org/) specially designed for Chevereto but still no luck with contribution.

Rather than going Open Source base then distribute plugins, I'm updating the entire thing as as monolith and then I will split the paid plugins once I get the revenue setup. I do this because I suck at driving Open Source projects, but with proprietary I have way better reception so I will focus there.

**Comment by rodber** [comment]
Hey there,

I'm still looking for maintainers and I'm willing to mentor/train anyone willing to take the responsibility. **If I get maintainers I commit myself to provide a legacy long-term edition that should work up to 2024** and I will also provide official Docker images for Chevereto-Free.

I'm willing to keep myself active and involved with Chevereto-Free long as I get help in this process.

That's all I ask.

**Comment by rodber** [comment]
Screw this, I will maintain this project in my personal account.
