### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [chevereto/Chevereto-Free#93]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by rodber** [comment]
Feel free to open a pull request with your patches, thank you.

You can also email me directly at my public email.

**Comment by rodber** [comment]
Thank you, I've patched the affected files for both editions (unreleased). I don't know how huntr works, let me know where we can send you the $ for taking time to report this.

Cheers.

**Comment by JamieSlome** [comment]
@rodber - for your awareness, we sponsor the vulnerability research for you!

However, if you would like to sponsor yourself and contribute more funds to vulnerability research, we support this too!

Just make sure to confirm the patch on the report!

**Comment by rodber** [comment]
Done, try it out and let me know if everything goes as expected. if you need to quickly try it out: https://github.com/chevereto/docker/tree/3.20

Running:

```sh
SOURCE=/Users/you/git/Chevereto-Free \
docker-compose \
    -p chevereto-free-dev \
    -f docker-compose/httpd-php-dev.yml \
    up
```

It will spawn at http://localhost:8930/

Once done, run this to sync the project code to the container:

```sh
docker exec -it chevereto-v3-dev_bootstrap \
    bash /var/www/sync.sh
```
