### ISSUE TITLE
Potential Security Vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [Chevereto/Chevereto-Free#94]
Hello,  - a potential high severity security vulnerability in your repository has been disclosed to huntr.

Visit report url and validate them 
https://huntr.dev/bounties/880c6dcd-023d-411a-b063-ac915e8ff99e/
Report details is only visible to repo-maintainer and reporter

**Comment by rodber** [comment]
Thanks, I encourage you to disclose it directly at https://chv.to/bug-tracking

I'm sorry but I won't signup for a service that access my private profile and my private email.

**Comment by ranjit-git** [comment]
@rodber 
no need to  signup if you dont want.
Plz share email address , so that report can be sent?

**Comment by rodber** [comment]
Here are the contact details: https://chevereto.com/contact

Kindly note that **we don't offer any bounty**.
