### ISSUE TITLE
Can't upgrade free version to 1.4.1

### ISSUE THREAD

**Issue by hamersky** [chevereto/Chevereto-Free#98]
Upgrade
A license key is required to upgrade to our main edition.
The system database schema will change, and the system files will get replaced. Don't forget to backup.
Your system settings, previous uploads, and all user-generated content will remain there.

?

**Comment by LiloBzH** [comment]
and manual upgrade is broken

"Fatal error: app/install is outdated. You need to re-upload app/install folder with the one from Chevereto 1.4.1"

**Comment by hamersky** [comment]
chow many files change from 1.4.0

**Comment by rodber** [comment]
Upgrade is not the same as update. For modified files you can check the commit history.

**Comment by hamersky** [comment]
Sorry - update from 1.4.0 to 1.4.1 - not work.

**Comment by rodber** [comment]
1.4.1 has been withdraw until further notice.
